        %include "include/syscalls.asm"
        %include "include/errno.asm"
        %include "include/file.asm"
        %include "include/mman.asm"
        %include "include/network.asm"
        %include "include/signal.asm"
        %include "include/socketcall.asm"
